AOV actualization
luxteam/jobs_test_houdini pull request #50
Opened 2023-03-21 13:49 UTC by Sofshik

https://rpr.cis.luxoft.com/job/USD-HoudiniPlugin-Manual/1249/

2023-03-22 14:55 UTC, Speedwag00n requested changes

2023-03-22 14:55 UTC, Speedwag00n commented on jobs/Scripts/usdParser.py
> +    def set_aov(self, aov):
Добавить новую структуру RenderProduct в самый конец файла не получится, т.к. структура USD файла более комплексна
Нужно посмотреть на структуру файла AOV_new.usda (ищи на NAS в /web/Assets/usd_houdini_autotests/AOV). Там уже есть структура def RenderProduct "renderproduct1"
Давай использовать этот файл в автотестах и менять в нем значения для выставления нужной AOV. Можно заранее модифицировать сам файл, если будет необходимость

2023-03-23 19:08 UTC, Sofshik commented
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/USD-HoudiniPlugin-Manual/1250/

2023-03-24 07:33 UTC, Speedwag00n requested changes

2023-03-24 07:33 UTC, Speedwag00n commented on jobs/Scripts/usdParser.py
> +        self.usd_data = re.sub(r'rel orderedVars = \[\s*]', f'rel orderedVars = [</Render/Products/Vars/{aov}>]', self.usd_data)
Стоит оставить комментарии, что делает каждая из строк

2023-03-24 07:41 UTC, Speedwag00n commented
Запущу полную сборку

2023-04-04 07:36 UTC, merged